export const CARACA_AUTH_START = 'CARACA_AUTH_START'
export const SET_TEAMNAME = 'SET_TEAMNAME'
export const UPDATE_USER = 'UPDATE_USER'

export const UPDATE_HEADER = 'UPDATE_HEADER'

export const INIT_QUESTIONS = 'INIT_QUESTIONS'
export const SET_QUESTIONS_LOCAL = 'SET_QUESTIONS_LOCAL'
export const INCREMENT_QUESTION = 'INCREMENT_QUESTION'
export const INCREMENT_RESPONSE = 'INCREMENT_RESPONSE'

export const SET_QUESTION = 'SET_QUESTION'

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const GET_CLASSEMENT = 'GET_CLASSEMENT';
/*
export const SET_ATTEMPT = 'SET_ATTEMPT';
export const UPDATE_ATTEMPT = 'UPDATE_ATTEMPT'
*/